---
title: "Script PRINCALS-FuzzyCluster"
author: "Martinez D, Darghan A, Rivera C"
output: 
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Package

```{r results='hide'}
library(readxl)
library(writexl)
library(dplyr)
library(Gifi)
library(fclust)
library(tidyverse)
library(fmsb)
library(plotly)
library(RColorBrewer)
library(viridis)
```

Data loading

```{r}
pre_df = read_excel('Datos FAMD.xlsx')
head(pre_df)
```

```{r}
df = pre_df
colnames(df) = paste0('var', seq(ncol(df)))

df = df %>%
  mutate_all(as.factor) %>% 
  as.data.frame()

head(df)
```

Categorical principal component analysis

```{r}
fitord <- princals(df, ndim = 6)  ## ordinal PCA
summary(fitord)
```


```{r}
# Biplot of 1 and 2 components
plot(fitord, "loadplot", plot.dim = c(1,2))
```

```{r}
# Percentage explained variance by component
vaf = 100 * fitord$evals/sum(fitord$evals)
graf_scree = ggplot()+
  aes(x=as.factor(seq(15)), y=vaf)+
  geom_col(fill = '#4682b4')+
  geom_text(aes(label = paste0(round(vaf,1), '%')), nudge_y = 1)+
  labs(x = 'Component',
       y = 'Percentage of the variance explained',
       title = 'Scree Plot PRINCAL')+
  theme_bw()
graf_scree
```

Fuzzy k-means clustering

```{r}
set.seed(2022)
ran_c = seq(2, 7, 1)
ran_m = seq(1.5, 1.9, .1)
xb_ = matrix(NA, nrow = length(ran_c), ncol = length(ran_m))
for(i in ran_c){
  ms = NULL
  for(j in ran_m){
    clust = FKM(fitord$objectscores, k = i, m = j)
    # Xie and Beni index
    xb = XB(clust$Xca,clust$U,clust$H,clust$m)
    ms = c(ms, xb)
  }
  xb_[i-1,]=ms
}
dimnames(xb_) = list('cluster'=ran_c, 'fuzziness'=ran_m)
round(xb_, 3)
```

```{r}
mej_xb = which(xb_ == min(xb_), arr.ind = TRUE)
ran_c[mej_xb[1]]
ran_m[mej_xb[2]]
```


```{r}
plot_ly(type = 'mesh3d',
        x = rep(ran_c, length(ran_m)),
        y = rep(ran_m, each = length(ran_c)),
        z = as.vector(xb_),
        intensity = as.vector(xb_),
        color = as.vector(xb_),
        colors = viridis(30)) %>% 
  layout(scene = list(xaxis=list(title='# cluster'),
                      yaxis=list(title='fuzziness'),
                      zaxis=list(title='Xie-Beni')))
```


```{r}
# Fuzzy with best k
set.seed(123)
clust = FKM(fitord$objectscores, k = 4, m = 1.6, index = 'XB')
grupo = clust$clus[,1]
table(grupo)
```

```{r}
df_res = df
colnames(df_res) = colnames(pre_df)

dfsl = list(
  total = cbind(df_res, grupo),
  grupo1 = df_res[grupo==1,],
  grupo2 = df_res[grupo==2,],
  grupo3 = df_res[grupo==3,],
  grupo4 = df_res[grupo==4,]
)
dfsl
```

```{r}
cat('\n\tCaracteristicas Grupo 1')
t(summary(dfsl[[1]]))
cat('\n\tCaracteristicas Grupo 2')
t(summary(dfsl[[2]]))
cat('\n\tCaracteristicas Grupo 3')
t(summary(dfsl[[3]]))
cat('\n\tCaracteristicas Grupo 4')
t(summary(dfsl[[4]]))
```

```{r}
df_res2 = df_res

cn = c(
  'v1' = 'Sex (v1)',
  'v2' = 'Range/Age (v2)',
  'v3' = 'Can read and write (v3)',
  'v4' = 'Higher education degree (v4)',
  'v5' = 'Education level (v5)',
  'v6' = 'Producer category - Fedepalma (v6)',
  'v7' = 'Adoption of Dichotomous Technology (v7)',
  'v8' = 'Work in activities other than farming (v8)',
  'v9' = 'Type of tenure (v9)',
  'v10' = 'Land use (v10)',
  'v11' = 'Uses irrigation system (v11)',
  'v12' = 'Uses fertilizers (v12)',
  'v13' = 'Has pest and disease management scheme (v13)',
  'v14' = 'Profits from palm cultivation (v14)',
  'v15' = 'Type of workers (v15)'
)
colnames(df_res2) = names(cn)

levels(df_res2$v1) = c('Male','Female')
levels(df_res2$v2) = c('<30','31-50','51-65','66-80','>81')
levels(df_res2$v3) = c('No','Yes')
levels(df_res2$v4) = c('No','Technician or Technologist','Professional')
levels(df_res2$v5) = c('Low','Medium','High')
levels(df_res2$v6) = c('<50 ha','>50 ha')
levels(df_res2$v7) = c('No','Yes')
levels(df_res2$v8) = c('No','Yes')
levels(df_res2$v9) = c('Inheritance succession', 'Owner with title', 'Holder', 'Tenant', 'Co-owner with title')
levels(df_res2$v10) = c('Exc production','Production and residence')
levels(df_res2$v11) = c('No','Yes')
levels(df_res2$v12) = c('No','Yes')
levels(df_res2$v13) = c('No','Yes')
levels(df_res2$v14) = c('0-500000', '500000-1500000', '1500000-3000000', '3000000-6000000', '>6000000')
levels(df_res2$v15) = c('Family, Wage earners', 'Family', 'Wage earners')

colnames(df_res2) = cn
# df_res2 = mutate_all(df_res2, str_to_lower)
head(df_res2)
```


```{r}
df_cont = list()
for(i in colnames(df_res2)){
  df_cont[[i]] = df_res2 %>% 
    mutate(v = paste0(i,'_',get(i)),
           v2 = paste0(str_extract(i, 'v[0-9]+'),'_',get(i)), # (str_extract(i, '\\((.*)\\)'))
           grupo = as.factor(grupo)) %>% 
    group_by(v, v2, grupo) %>% 
    summarise(n = n()) %>% 
    mutate(porc = 100 * n/sum(n))
}

df_cont_tot = do.call(rbind, df_cont)
df_cont_tot$ord = nrow(df_cont_tot):1
df_cont_tot

# Los nombres de los grupos son: 
# Grupo 1 Poblaci贸n vulnerable 
# Grupo 2 Poblaci贸n con liderazgo femenino 
# Grupo 3 Poblaci贸n diversificada 
# Grupo 4 Poblaci贸n con exclusividad en cultivos de palma de aceite

levels(df_cont_tot$grupo) = c(
  'Vulnerable population',
  'Population with female leadership',
  'Diversified population',
  'Population with exclusivity in oil palm crops'
)
```

```{r}
graf_porc = df_cont_tot %>% 
  ggplot()+
  aes(porc, fct_reorder(v, ord), fill = grupo)+
  geom_bar(stat = 'identity')+
  scale_fill_viridis_d()+
  labs(x='Percentage',
       y='',
       fill='Group')+
  theme_bw()+
  theme(legend.position = 'bottom',
        legend.direction = 'vertical',
        legend.justification = 'top')

graf_porc
```


```{r}
df_cont_ = do.call(rbind, df_cont[1:5])
nom_group = c(
  'Vulnerable population',
  'Population with\nfemale leadership',
  'Diversified population',
  'Population with exclusivity\nin oil palm crops'
)
df_radar_tot = df_cont_ %>% 
  reshape2::dcast('grupo~v2', value.var = 'porc')
df_radar_tot = df_radar_tot[,-1]

df_radar_tot[is.na(df_radar_tot)]=0

df_radar_tot_g = rbind(rep(100, ncol(df_radar_tot)), rep(0,ncol(df_radar_tot)), df_radar_tot)

color = RColorBrewer::brewer.pal(4, 'Set1')
color_alpha = paste0(color, '40')
radarchart(df_radar_tot_g,
           cglty = 1,       # Grid line type
           cglcol = "gray", # Grid line color
           pcol = color,
           plwd = 2.5,        # Width for each line
           plty = 1,
           pfcol = color_alpha,
           vlcex = 1.5)

legend(-1.55, -0.75, horiz = F,
       legend = nom_group,
       bty = "n", pch = 16,
       col = RColorBrewer::brewer.pal(4, 'Set1'),
       text.col = "grey25", pt.cex = 3, cex = 1.5)
```


```{r}
df_cont_ = do.call(rbind, df_cont[6:10])
df_radar_tot = df_cont_ %>% 
  reshape2::dcast('grupo~v2', value.var = 'porc')
df_radar_tot = df_radar_tot[,-1]
df_radar_tot[is.na(df_radar_tot)]=0

df_radar_tot_g = rbind(rep(100, ncol(df_radar_tot)), rep(0,ncol(df_radar_tot)), df_radar_tot)


color = RColorBrewer::brewer.pal(4, 'Set1')
color_alpha = paste0(color, '40')

radarchart(df_radar_tot_g,
           cglty = 1,       # Grid line type
           cglcol = "gray", # Grid line color
           pcol = color,
           plwd = 2.5,        # Width for each line
           plty = 1,
           pfcol = color_alpha,
           vlcex = 1.5)

legend(-1.55, -0.75, horiz = F,
       legend = nom_group,
       bty = "n", pch = 16,
       col = RColorBrewer::brewer.pal(4, 'Set1'),
       text.col = "grey25", pt.cex = 3, cex = 1.5)
```

```{r}
df_cont_ = do.call(rbind, df_cont[11:15])
df_radar_tot = df_cont_ %>% 
  reshape2::dcast('grupo~v2', value.var = 'porc')
df_radar_tot = df_radar_tot[,-1]
df_radar_tot[is.na(df_radar_tot)]=0

df_radar_tot_g = rbind(rep(100, ncol(df_radar_tot)), rep(0,ncol(df_radar_tot)), df_radar_tot)

color = RColorBrewer::brewer.pal(4, 'Set1')
color_alpha = paste0(color, '40')

radarchart(df_radar_tot_g,
           cglty = 1,       # Grid line type
           cglcol = "gray", # Grid line color
           pcol = color,
           plwd = 2.5,        # Width for each line
           plty = 1,
           pfcol = color_alpha,
           vlcex = 1.5)

legend(-1.55, -0.75, horiz = F,
       legend = nom_group,
       bty = "n", pch = 16,
       col = RColorBrewer::brewer.pal(4, 'Set1'),
       text.col = "grey25", pt.cex = 3, cex = 1.5)
```
